#
# idbg-id/Makefile - Build the IDBG identification utility
#
# Written 2010 by Werner Almesberger
# Copyright 2010 Werner Almesberger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#


MAIN = idbg-id
OBJS = ../lib/usb.o ../lib/identify.o

include ../Makefile.common

CFLAGS += -I../../fw/include
