#
# idbg-i2c/Makefile - Build the IDBG I2C read/write utility
#
# Written 2008-2010 by Werner Almesberger
# Copyright 2008-2010 Werner Almesberger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#


MAIN = idbg-i2c
OBJS = ../lib/usb.o ../lib/identify.o

include ../Makefile.common

CFLAGS += -I../../fw/include
