#
# idbg-norwp/Makefile - Build the IDBG GTA02 NOR write-protect control utility
#
# Written 2009 by Werner Almesberger
# Copyright 2009 Werner Almesberger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#


MAIN=idbg-norwp

include ../Makefile.common

CFLAGS += -I../../fw/idbg -I../../fw/include
