#
# tools/Makefile - Build the IDBG-specific tools
#
# Written 2008-2010 by Werner Almesberger
# Copyright 2008-2010 Werner Almesberger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#


DIRS=idbg-gpio idbg-reset idbg-con idbg-i2c idbg-norwp idbg-id idbg-nnboot

include ../Makefile.recurse
